
#ifndef ARX_CONFIGURE_H
#define ARX_CONFIGURE_H

// Thread & process control
#define ARX_HAVE_PTHREADS 0
#define ARX_HAVE_PRCTL 0
#define ARX_HAVE_PTHREAD_SETNAME_NP 0
#define ARX_HAVE_PTHREAD_SET_NAME_NP 0
#define ARX_HAVE_SCHED_GETSCHEDULER 0
#define ARX_HAVE_NANOSLEEP 0
#define ARX_HAVE_FORK 0
#define ARX_HAVE_SETPGID 0
#define ARX_HAVE_EXECVP 0
#define ARX_HAVE_POSIX_SPAWNP 0
#define ARX_HAVE_UNISTD_ENVIRON 0
#define ARX_HAVE_WAITPID 0
#define ARX_HAVE_SIGACTION 0
#define ARX_HAVE_GETPID 0
#define ARX_HAVE_GETUID 0
#define ARX_HAVE_GETGID 0
#define ARX_HAVE_KILL 0
#define ARX_HAVE_SETRLIMIT 0

// Filesystem & I/O
#define ARX_HAVE_POSIX_FILESYSTEM 0
#define ARX_HAVE_WIN32_FILESYSTEM 1
#define ARX_HAVE_BOOST_FILESYSTEM_V3 0
#define ARX_HAVE_READLINK 0
#define ARX_HAVE_OPEN 0
#define ARX_HAVE_O_CLOEXEC 0
#define ARX_HAVE_FCNTL 0
#define ARX_HAVE_DUP2 0
#define ARX_HAVE_PIPE 0
#define ARX_HAVE_PIPE2 0
#define ARX_HAVE_READ 0
#define ARX_HAVE_CLOSE 0
#define ARX_HAVE_ISATTY 0
#define ARX_HAVE_THREADSAFE_READDIR 0
#define ARX_HAVE_FPATHCONF 0
#define ARX_HAVE_PATHCONF 0
#define ARX_HAVE_NAME_MAX 0
#define ARX_HAVE_PC_NAME_MAX 0
#define ARX_HAVE_PC_CASE_SENSITIVE 0
#define ARX_HAVE_DIRFD 0
#define ARX_HAVE_FSTATAT 0
#define ARX_HAVE_AT_SYMLINK_NOFOLLOW 0
#define ARX_HAVE_CHDIR 0

// Video backend
#define ARX_HAVE_EPOXY 1
#define ARX_HAVE_GLEW 0
#define ARX_HAVE_GLX 0
#define ARX_HAVE_EGL 0
#define ARX_HAVE_GL_STATIC 1

// Audio backend
#define ARX_HAVE_OPENAL 1
#define ARX_HAVE_OPENAL_EFX 1
#define ARX_HAVE_OPENAL_HRTF 1

// Input backend
#define ARX_HAVE_SDL1 0
#define ARX_HAVE_SDL2 1
#define ARX_HAVE_SDL2_X11 0

// Crash handler
#define ARX_HAVE_CRASHHANDLER_POSIX 0
#define ARX_HAVE_CRASHHANDLER_WINDOWS 1

// Endianness
#define ARX_HAVE_BUILTIN_BSWAP16 0
#define ARX_HAVE_BUILTIN_BSWAP32 0
#define ARX_HAVE_BUILTIN_BSWAP64 0
#define ARX_HAVE_BSWAP_16 0
#define ARX_HAVE_BSWAP_32 0
#define ARX_HAVE_BSWAP_64 0

// Misc POSIX / Linux features
#define ARX_HAVE_DLSYM 0
#define ARX_HAVE_BACKTRACE 0
#define ARX_HAVE_WORDEXP 0
#define ARX_HAVE_UNAME 0
#define ARX_HAVE_GETRUSAGE 0
#define ARX_HAVE_SYSCONF 0
#define ARX_HAVE_GETEXECNAME 0
#define ARX_HAVE_SYSCTL 0
#define ARX_HAVE_SYSCTLBYNAME 0
#define ARX_HAVE_SETENV 0
#define ARX_HAVE_UNSETENV 0
#define ARX_HAVE_CONFSTR 0

// Architure-specific features
#define ARX_HAVE_GET_CPUID 0
#define ARX_HAVE_GET_CPUID_MAX 0
#define ARX_HAVE_XMMINTRIN 1
#define ARX_HAVE_PMMINTRIN 1
#define ARX_HAVE_BUILTIN_IA32_FXSAVE 0

// Assert intercepts
#define ARX_HAVE_LIBCPP_VERBOSE_ABORT 0
#define ARX_HAVE_GLIBCXX_ASSERT_FAIL 0

// Build system
#define UNITY_BUILD 0

// Defaults
#define ARX_DEBUG_GL 0

#endif // ARX_CONFIGURE_H
